### ISSUE TITLE
using `kill()` does not fully reset state

### ISSUE THREAD

**Issue by reviewher** [alewin/useWorker#119]
https://github.com/alewin/useWorker/blob/master/packages/useWorker/src/useWorker.ts#L64

If the `kill` method is called from user code, `isRunning` is never reset and https://github.com/alewin/useWorker/blob/master/packages/useWorker/src/useWorker.ts#L149 error is tripped the next time the worker is used.

`setWorkerStatus(WORKER_STATUS.ERROR)` or `isRunning.current = false` in that spot fixes the problem

**Comment by ashish-r** [comment]
In [this](https://icji4.csb.app/sorting) sorting example also, the kill functionality is not working.

**Comment by ashish-r** [comment]
Created the PR for fix [here](https://github.com/alewin/useWorker/pull/122)

@alewin @zant please review

**Comment by Arif-un** [comment]
Still the same problem, any update on this issue?

**Comment by TianJianJun727** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by ashish-r** [comment]
@Arif-un [this](https://github.com/alewin/useWorker/pull/122) pr is still not merged.

@alewin @zant guys the PR is approved, anything I should change/take care of? If not can we please merge?

**Comment by sheron184** [comment]
Is this issue fixed?

**Comment by alewin** [comment]
released [`useWorker@4.1.0`](https://www.npmjs.com/package/@koale/useworker) with the fixes ( https://github.com/alewin/useWorker/pull/122 )
thanks @ashish-r 

Apologies for the long wait, but due to personal and work-related reasons, I wasn’t able to maintain the library.
I’m well aware that forks and alternatives have emerged in the meantime, and I’m glad for it because the library was intentionally open-source with an MIT license to prevent issues like this.

Together with the new maintainer, @naorpeled, we are working to stabilize useWorker and add new features in the coming months. :)
