### ISSUE TITLE
Error's with async functions

### ISSUE THREAD

**Issue by IljaDaderko** [alewin/useWorker#30]
I was trying to debug this to find out the cause, but was unsuccessful, basically when `useWorker` is passed a simple function like this everything is working:

```ts
function sum(num1: number, num2: number) {
  return num1 + num2;
}
// ...
const [sumWorker] = useWorker(sum);
const result = await sumWorker(1, 2);
```

However, I was trying to utilise worker to load images in a worker i.e

```ts
async function fetchImage(src: string) {
  const response = await fetch(src);
  const blob = await response.blob();
  const objectUrl = URL.createObjectURL(blob);

  return objectUrl;
}

// ...
const [fetchImageWorker] = useWorker(fetchImage);
const result = await fetchImageWorker("https://...");
```

I am getting a babel / webpack error:
> ReferenceError: regeneratorRuntime is not defined

**Comment by alewin** [comment]
@IljaDaderko the error occurred during a development on `codesandbox.io` or in a normal react project?

**Comment by IljaDaderko** [comment]
Development, when used inside next.js project.

**Comment by alewin** [comment]
I did some tests @IljaDaderko and I haven't encountered the problem, is it possible that it runs differently using Next.js? : /

**A few notes:**

Running this function inside the **WebWorker**
```javascript
async function fetchImage(src: string) {
  const response = await fetch(src);
  const blob = await response.blob();
  const objectUrl = URL.createObjectURL(blob);

  return objectUrl;
}
```
I noticed that: by creating a `URL` with `createObjectURL` inside the **Web Worker**, the `url` stay alive as long as it has a reference, but since the result of the function performed with the worker sends the response via `event message`, I suppose that browser remove the `BlobURL` to do some garbage collector cleaning.
To get around this, you could just pass the `BLOB` and leave the caller generate the `URL` (not the Worker).

---

**Some clarifications:**
- If you use SSR maybe you shouldn't need to `fetch` with webworker
- The `fetch` WebAPI is performed asynchronously and it's non-blocking, so there is no need to run it with a Web Worker

---

Here my test code:

**Code:**
```javascript
import { useWorker } from '@koale/useworker'

async function fetchImage(src) {
  const response = await fetch(src);
  const blob = await response.blob();
  return blob;
}


function App() {
  const [fetchImageWorker] = useWorker(fetchImage);
  const [logo, setLogo] = React.useState()

  React.useEffect(() => {
    async function testFetchImageWorker(url){
      const blob = await fetchImageWorker(url);
      const imageUrl = URL.createObjectURL(blob);
      setLogo(imageUrl)
    }

    const url = 'https://create-react-app.dev/img/logo.svg'
    testFetchImageWorker(url)
  }, [])

```

let me know if you agree, otherwise I'll try to investigate better

**Comment by IljaDaderko** [comment]
I have tried it outside of next js environment and everything worked fine. So I'll close this issue and will investigate further. Likely some webpack config stuff I am missing.

**Comment by afijal** [comment]
> I have tried it outside of next js environment and everything worked fine. So I'll close this issue and will investigate further. Likely some webpack config stuff I am missing.

Did you find the root cause?
