### ISSUE TITLE
async function error

### ISSUE THREAD

**Issue by lxfu1** [alewin/useWorker#68]
**[Required] Describe the bug**
异步函数报错

**[Optional] To Reproduce**
```tsx
import React from 'react';
import { useWorker } from '@koale/useworker';

const Example = () => {
  const numbers = [...Array(5000000)].map(e => ~~(Math.random() * 1000000));
  const sortNumbers = async (nums: number[]) => {
    // test async
    const res = await nums.sort();
    return res;
  };
  const [sortWorker] = useWorker(sortNumbers);

  const runSort = async () => {
    const result = await sortWorker(numbers); // non-blocking UI
    console.log('End.');
  };

  return (
    <button type="button" onClick={runSort}>
      Run Sort
    </button>
  );
};

export default Example;
```

![image](https://user-images.githubusercontent.com/31396322/88666777-1bd8d380-d113-11ea-82cf-7fdf556e408d.png)

**Comment by gonzachr** [comment]
Hi @lxfu1! This error is ocurring because of transpiling being made on async functions, which is the case in CodeSandbox for example. Where the async function is converted to a generator with Babel.

This is the error I get inside a try/catch in CodeSandbox: `ReferenceError: _asyncToGenerator2 is not defined`. This is similar to what's going on on #87. We will update the documentation to point this out. 

Thanks for reporting!
